# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from passwin import Ui_PassWin
from verification import Ui_Form
import random
import sqlite3
import string
import cv2
import numpy as np
import face_recognition
import os
import time 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        #####################################################
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        #####################################################
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 361)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(610, 361))
        MainWindow.setMaximumSize(QtCore.QSize(610, 361))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(610, 361))
        self.centralwidget.setObjectName("centralwidget")
        self.view_pass = QtWidgets.QPushButton(self.centralwidget)
        self.view_pass.setGeometry(QtCore.QRect(400, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.view_pass.setFont(font)
        self.view_pass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.view_pass.setMouseTracking(False)
        self.view_pass.setStyleSheet("QPushButton{\n"
"background-color: rgb(17, 214, 139);\n"
"color:black;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 39);\n"
"color:rgb(17, 214, 139);\n"
"border: 1px solid rgb(17, 214, 139);\n"
"}")
        self.view_pass.setObjectName("view_pass")
        self.website = QtWidgets.QLabel(self.centralwidget)
        self.website.setGeometry(QtCore.QRect(40, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.website.setFont(font)
        self.website.setStyleSheet("color:white")
        self.website.setObjectName("website")
        self.username = QtWidgets.QLabel(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(40, 130, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.username.setFont(font)
        self.username.setStyleSheet("color:white")
        self.username.setObjectName("username")
        self.entry1 = QtWidgets.QLineEdit(self.centralwidget)
        self.entry1.setEnabled(True)
        self.entry1.setGeometry(QtCore.QRect(180, 100, 130, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.entry1.setFont(font)
        self.entry1.setMouseTracking(True)
        self.entry1.setStyleSheet("QLineEdit{\n"
"background-color: rgba(0,0,0,0);\n"
"color:white;\n"
"border:none;\n"
"border-bottom: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgba(0,0,0,0);\n"
"color:white;\n"
"border:none;\n"
"border-bottom: 1px solid rgb(17, 214, 139);\n"
"}")
        self.entry1.setObjectName("entry1")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(330, 90, 16, 231))
        self.line.setStyleSheet("background-color: none;")
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.entry2 = QtWidgets.QLineEdit(self.centralwidget)
        self.entry2.setGeometry(QtCore.QRect(180, 130, 130, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.entry2.setFont(font)
        self.entry2.setStyleSheet("QLineEdit{\n"
"background-color: rgba(0,0,0,0);\n"
"color:white;\n"
"border:none;\n"
"border-bottom: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgba(0,0,0,0);\n"
"color:white;\n"
"border:none;\n"
"border-bottom: 1px solid rgb(17, 214, 139);\n"
"}")
        self.entry2.setObjectName("entry2")
        self.entry3 = QtWidgets.QLineEdit(self.centralwidget)
        self.entry3.setGeometry(QtCore.QRect(180, 160, 130, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.entry3.setFont(font)
        self.entry3.setStyleSheet("QLineEdit{\n"
"background-color: rgba(0,0,0,0);\n"
"color:white;\n"
"border:none;\n"
"border-bottom: 1px solid rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"background-color: rgba(0,0,0,0);\n"
"color:white;\n"
"border:none;\n"
"border-bottom: 1px solid rgb(17, 214, 139);\n"
"}")
        self.entry3.setInputMask("")
        self.entry3.setMaxLength(15)
        self.entry3.setClearButtonEnabled(False)
        self.entry3.setObjectName("entry3")
        self.pass_len = QtWidgets.QLabel(self.centralwidget)
        self.pass_len.setGeometry(QtCore.QRect(40, 160, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pass_len.setFont(font)
        self.pass_len.setStyleSheet("color:white")
        self.pass_len.setObjectName("pass_len")
        self.passwd = QtWidgets.QLabel(self.centralwidget)
        self.passwd.setGeometry(QtCore.QRect(40, 240, 81, 18))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.passwd.setFont(font)
        self.passwd.setStyleSheet("color: white;")
        self.passwd.setObjectName("passwd")
        self.save_data = QtWidgets.QPushButton(self.centralwidget)
        self.save_data.setGeometry(QtCore.QRect(90, 280, 72, 23))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.save_data.setFont(font)
        self.save_data.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_data.setStyleSheet("QPushButton{\n"
"background-color: rgb(17, 214, 139);\n"
"color:black;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 39);\n"
"color:rgb(17, 214, 139);\n"
"border: 1px solid rgb(17, 214, 139);\n"
"}")
        self.save_data.setObjectName("save_data")
        self.reset_data = QtWidgets.QPushButton(self.centralwidget)
        self.reset_data.setGeometry(QtCore.QRect(167, 280, 72, 23))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.reset_data.setFont(font)
        self.reset_data.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reset_data.setStyleSheet("QPushButton{\n"
"background-color: white;\n"
"color:black;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:black;\n"
"color:white;\n"
"border: 1px solid white;\n"
"}")
        self.reset_data.setObjectName("reset_data")
        self.gen_pass = QtWidgets.QPushButton(self.centralwidget)
        self.gen_pass.setGeometry(QtCore.QRect(40, 200, 271, 30))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.gen_pass.setFont(font)
        self.gen_pass.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gen_pass.setStyleSheet("QPushButton{\n"
"background-color: rgb(17, 214, 139);\n"
"color:black;\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(0, 0, 39);\n"
"color:rgb(17, 214, 139);\n"
"border: 1px solid rgb(17, 214, 139);\n"
"}")
        self.gen_pass.setCheckable(True)
        self.gen_pass.setAutoDefault(False)
        self.gen_pass.setDefault(False)
        self.gen_pass.setFlat(False)
        self.gen_pass.setObjectName("gen_pass")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 611, 361))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 39, 255), stop:1 rgba(39, 18, 62, 255));\n"
"")
        self.widget.setObjectName("widget")
        self.app_name = QtWidgets.QLabel(self.widget)
        self.app_name.setGeometry(QtCore.QRect(0, 30, 611, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.app_name.setFont(font)
        self.app_name.setStyleSheet("background-color: none;\n"
"color: rgb(255, 255, 255);")
        self.app_name.setAlignment(QtCore.Qt.AlignCenter)
        self.app_name.setWordWrap(False)
        self.app_name.setObjectName("app_name")
        self.title_bar = QtWidgets.QFrame(self.widget)
        self.title_bar.setGeometry(QtCore.QRect(0, 0, 611, 30))
        self.title_bar.setStyleSheet("background-color: rgb(0, 0, 29);")
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.btn_panel = QtWidgets.QFrame(self.title_bar)
        self.btn_panel.setGeometry(QtCore.QRect(535, 0, 70, 30))
        self.btn_panel.setStyleSheet("background-color:none;")
        self.btn_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn_panel.setObjectName("btn_panel")
        self.minimize_btn = QtWidgets.QPushButton(self.btn_panel)
        self.minimize_btn.setGeometry(QtCore.QRect(0, 0, 30, 30))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.minimize_btn.setFont(font)
        self.minimize_btn.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"background-image: url(C:/Python36/PROJECT/Password Buddy/icon/icons8-minimize-window-30.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius:1px;\n"
"background-color: rgb(0, 0, 52);\n"
"background-image: url(C:/Python36/PROJECT/Password Buddy/icon/icons8-minimize-window-30.png);}")
        self.minimize_btn.setText("")
        self.minimize_btn.setIconSize(QtCore.QSize(30, 30))
        self.minimize_btn.setAutoDefault(False)
        self.minimize_btn.setDefault(False)
        self.minimize_btn.setFlat(True)
        self.minimize_btn.setObjectName("minimize_btn")
        self.close_btn = QtWidgets.QPushButton(self.btn_panel)
        self.close_btn.setEnabled(True)
        self.close_btn.setGeometry(QtCore.QRect(40, 0, 30, 30))
        self.close_btn.setAutoFillBackground(False)
        self.close_btn.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"background-image: url(C:/Python36/PROJECT/Password Buddy/icon/icons8-multiply-30.png);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border-radius:1px;\n"
"background-color: rgb(19, 26, 59);\n"
"background-image: url(C:/Python36/PROJECT/Password Buddy/icon/icons8-multiply-30.png);\n"
"}")
        self.close_btn.setText("")
        self.close_btn.setAutoDefault(False)
        self.close_btn.setDefault(False)
        self.close_btn.setFlat(True)
        self.close_btn.setObjectName("close_btn")
        self.title_panel = QtWidgets.QFrame(self.title_bar)
        self.title_panel.setGeometry(QtCore.QRect(0, 0, 130, 30))
        self.title_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_panel.setObjectName("title_panel")
        self.title = QtWidgets.QLabel(self.title_panel)
        self.title.setGeometry(QtCore.QRect(40, 0, 90, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.title.setFont(font)
        self.title.setStyleSheet("background-color: none;\n"
"color: white;")
        self.title.setObjectName("title")
        self.icon = QtWidgets.QLabel(self.title_panel)
        self.icon.setGeometry(QtCore.QRect(10, 5, 20, 20))
        self.icon.setStyleSheet("background-color:none;")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("C:/Python36/PROJECT/Password Buddy/icon/pm.ico"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.title_bar.raise_()
        self.app_name.raise_()
        self.display_pass = QtWidgets.QLabel(self.centralwidget)
        self.display_pass.setGeometry(QtCore.QRect(180, 240, 130, 16))
        self.display_pass.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.display_pass.setStyleSheet("background-color: rgb(0, 0, 39);\n"
"color:rgb(17, 214, 139);\n"
"border: 1px solid rgb(17, 214, 139);\n"
"border-radius:2px;")
        self.display_pass.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.display_pass.setFrameShadow(QtWidgets.QFrame.Plain)
        self.display_pass.setObjectName("display_pass")
        self.widget.raise_()
        self.view_pass.raise_()
        self.website.raise_()
        self.username.raise_()
        self.entry1.raise_()
        self.line.raise_()
        self.entry2.raise_()
        self.entry3.raise_()
        self.pass_len.raise_()
        self.passwd.raise_()
        self.save_data.raise_()
        self.reset_data.raise_()
        self.gen_pass.raise_()
        self.display_pass.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.gen_pass.clicked.connect(self.passgen)
        self.save_data.clicked.connect(self.save)
        self.reset_data.clicked.connect(self.entry1.clear)
        self.reset_data.clicked.connect(self.entry2.clear)
        self.reset_data.clicked.connect(self.entry3.clear)
        self.reset_data.clicked.connect(self.display_pass.clear)
        self.view_pass.clicked.connect(self.masterPass)
        self.close_btn.clicked.connect(MainWindow.close)
        self.minimize_btn.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.view_pass.setText(_translate("MainWindow", "VIEW SAVED PASSWORDS"))
        self.website.setText(_translate("MainWindow", "WEBSITE"))
        self.username.setText(_translate("MainWindow", "USERNAME"))
        self.entry1.setPlaceholderText(_translate("MainWindow", "www.website.com"))
        self.entry2.setPlaceholderText(_translate("MainWindow", "username"))
        self.entry3.setPlaceholderText(_translate("MainWindow", "8-15"))
        self.pass_len.setText(_translate("MainWindow", "PASSWORD LENGTH"))
        self.passwd.setText(_translate("MainWindow", "PASSWORD"))
        self.save_data.setText(_translate("MainWindow", "SAVE"))
        self.reset_data.setText(_translate("MainWindow", "RESET"))
        self.gen_pass.setText(_translate("MainWindow", "GENERATE PASSWORD"))
        self.app_name.setText(_translate("MainWindow", "Password Buddy"))
        self.title.setText(_translate("MainWindow", "Password Buddy"))


    def passgen(self, password_char):
        chars = "abcdefghijklmnopqrxtuvwxyz1234567890ABCDEFGHIJKLMNOPQRXTUVWXYZ!@#$%^&*"
        while 1:
            length = int(self.entry3.text())
            password_char = ''.join(random.choices(chars, k=length))
            self.display_pass.setText(password_char)
            break
        
    
    def messagebox(self,title):
        mess=QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setText("Password Saved Successfully!")
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.buttonClicked.connect(self.entry1.clear)
        mess.buttonClicked.connect(self.entry2.clear)
        mess.buttonClicked.connect(self.entry3.clear)
        mess.buttonClicked.connect(self.display_pass.clear)
        mess.exec_()
   
    def save(self):
        db=sqlite3.connect("C:/Python36/PROJECT/Password Buddy/PassDB.db")
        website=self.entry1.text()
        username=self.entry2.text()
        password=self.display_pass.text()
        dbase=db.cursor()
        dbase.execute("INSERT into passwords values(?,?,?)", (website,username,password))
        db.commit()
        if (dbase):
           self.messagebox("Congrats!")
    
    def masterPass(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Form()
        self.ui.setupUi(self.window)
        self.window.show()
     
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui=Ui_PassWin()
        self.ui.setupUi(self.window)
        self.window.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
